language: node_js
node_js:
  - 13.2.0
cache: npm
deploy:
  provider: pages
  skip_cleanup: true
  github_token: '$GITHUB_TOKEN'
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: RHazmoS/QgXTHTWEf8lNl4zgqBimpHoBPMpJwBJsNgOCzzs6KB89iRsxU76ta6AqBiSiCbQ7Md4Dz/SBqqHoOuRKJaNTpO6M8uOB4iDgj3uh1gxDW62whPcmbym097x0huniDvweLuNWvKUPU4V8C52564AweYxkHwNFaUAZqLsVShldvhfbVv/ymj5hjxx3Jy3s8HT+ndCoh/hbFSa1xKpFFZYWm4WO+Sxuc/I5KegHWhLJMfKlnfa2JtgFd4+tjslTu3y470WWrvSTRct20KrrO3E1cTROJBpnX58jZDOFzwRW2I6/B0e94dU3PZY75IxL3HlfvQ/2mq7zrCHY6dq8RHv8l1gQ+qyVVxiGWX7dnGgoB+4gDlsvHKL/LbQG91ig3Ep+sGGY1yZ1v0AKogrt7KsPjD4PV8zQ8BQtCzXVPNN34XIUaVWqtMQt37SR69Fww7kQGQI541sfzxznHl6KI1WO65T21wKEKDFqeDt+S50wlkttM4T4yk6IZBTia2QsyILMRJy7J9JlqQvtqtwXSUMU1QPQcEkRcDcRhT2XpvivQHcbZNh8JiZuRQHWgw0xYK8SIeUPqD+eJo+pNUw3bfsmEkBEmDdTxmOfQARDw4fIO9E2hLRt+JafA+vKX0N2us/TNPelE7Uh9cEJIFLaLhJ68+Zz6gH/HUiFvjY=
